title: Transfer Me It
email: hello@transferme.it
recaptcha:
  pub: 6Le8h0gUAAAAAIhTxvNX5OJ2RQJQcLbR5vwsuesv
  priv: 6Le8h0gUAAAAABmMk4loL_UlQWA4E-Pko4hobnxu
meta:
  keywords: transfer me it, transfermeit, file, send, transfer, me, it, transfer, file transfer, send files, mac, osx, mac to mac
  description: A minimal file transfer app for MacOS.
app:
  version:
    num: 0.04
    description: >
      <h2>New Features</h2>

      <h2>Bugs</h2>

      <h4>Untested Release</h4>
      Thank you for testing!<br><br>
      Maximilian Mitchell
  dmg: Transfer Me It.dmg