version: '3.2'
services:
  app:
    image: maxisme/transferme.it:latest
    env_file:
      - ".env"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transfermeit.rule=Host(`transferme.it`)"
      - "traefik.http.routers.transfermeit.entrypoints=websecure"
      - "traefik.http.routers.transfermeit.tls.certresolver=letsencrypt"
      - "traefik.http.services.transfermeit.loadbalancer.server.port=8080"
    networks:
      - traefik

networks:
  traefik:
    external: true